In [3]:
import numpy as np

In [46]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [47]:
b = np.array(range(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
c = np.array(list({1, 2, 3, 4, 5}))
c

array([1, 2, 3, 4, 5])

In [49]:
matrix = np.array([[1,2, 3], [2, 3, 4]])
print(matrix)

[[1 2 3]
 [2 3 4]]


In [50]:
tensor = np.array([[[1, 2, 3], [2, 3, 4]], [[3, 4, 5], [4, 5, 6]], [[5, 6, 7], [6, 7, 8]]])
tensor

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]],

       [[5, 6, 7],
        [6, 7, 8]]])

In [51]:
matrix += 5
matrix

array([[6, 7, 8],
       [7, 8, 9]])

In [52]:
matrix

array([[6, 7, 8],
       [7, 8, 9]])

In [53]:
matrix = matrix + matrix
matrix

array([[12, 14, 16],
       [14, 16, 18]])

In [54]:
matrix = np.array([[1,2, 3], [2, 3, 4]])

In [55]:
matrix

array([[1, 2, 3],
       [2, 3, 4]])

In [56]:
matrix = matrix * matrix

In [57]:
matrix

array([[ 1,  4,  9],
       [ 4,  9, 16]])

In [58]:
matrix.shape

(2, 3)

In [59]:
tensor.shape

(3, 2, 3)

In [60]:
matrix.dtype

dtype('int64')

In [61]:
matrix.ndim

2

In [62]:
c = np.array([1.1, 2, 3, 4], dtype="int64")

In [63]:
print(c)
print(c.shape)
print(c.dtype)

[1 2 3 4]
(4,)
int64


In [64]:
s = np.array(list("abcedf"))
s

array(['a', 'b', 'c', 'e', 'd', 'f'], dtype='<U1')

In [65]:
polje = np.array([[1, 2], [1, 2, 3]])
polje # ne postoji defultni nacin da popunimo vrijednosit koje nema

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

#### drugi nacini stvaranja ndarray-a

In [40]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [42]:
a = np.zeros((3, 3, 2))
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [44]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [69]:
c = np.empty((2,1))
c # random vrijednosti

array([[0.e+000],
       [5.e-324]])

In [71]:
a = range(15)
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [73]:
a = np.arange(15) # !! ista stvar kao obican range(15) u pythonu samo sto ovdje se odmah vraca NUMPY array
                  #    tj ndarray a u ypthonu bi se samo vratio generator tih brojeva, i ond abi ga mi pretrovili u list ili iterirali po njemu
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
b = np.array(list(range(15)))  # ista stvar
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
matrix

array([[ 1,  4,  9],
       [ 4,  9, 16]])

In [80]:
o = np.ones(matrix.shape, dtype=matrix.dtype)
o

array([[1, 1, 1],
       [1, 1, 1]])

In [83]:
o = np.ones_like(matrix)
o

array([[1, 1, 1],
       [1, 1, 1]])

In [85]:
f = np.full(shape=(2, 2, 3), fill_value=2, dtype="int64")
f

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [87]:
i = np.identity(n= 5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
b = np.ones((2, 2), dtype=np.int64)
b

array([[1, 1],
       [1, 1]])

In [89]:
a = np.array([1, 2, 3, 4, 5])
a.dtype

dtype('int64')

In [93]:
fp_a = a.astype(np.float64) # Na ovaj način mozemo promjneiit data type tj dtype objekta i nacin na
                            # koji se on memoriji, u pocektu je bio int64 sta je float, a metodu smo pozvali nad
                            # postojecim np arrayom, tj ndarray-om
        # ime_polja.astype(np.neki tip) UVIJEK stvara i vraca novo polje
fp_a

array([1., 2., 3., 4., 5.])

In [94]:
r = np.arange(20)
r = r / 20
r

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [98]:
o = np.ones((2,2), dtype=np.float64)
o.dtype

dtype('float64')

In [107]:
a = np.array([1, 2, 3, 4, 5])
b = np.zeros((3, 5))
rez = a > b

In [112]:
all(rez.reshape((15, )))
any(rez.reshape(15))

True

### Indexing i slicing

In [114]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [119]:
a[5]

5

In [121]:
a[5:8]

array([5, 6, 7])

In [122]:
a[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [123]:
b = a[:5]
b

array([0, 1, 2, 3, 4])

In [124]:
b[:2] = 8
b

array([8, 8, 2, 3, 4])

In [132]:
a = [1, 2, 3, 4, 5]
a[:2] = [8, 8] # u obicnom pythonu s emora ovako postvaiti lista, jer On nema mogucnost brodcastanja
print(a, "obicna pyhton lista")       # Dok se u Numpy sve to moze brodcastitati

b[:2] = 8
print(b, "numpy")

[8, 8, 3, 4, 5] obicna pyhton lista
[8 8 2 3 4] numpy


In [133]:
a = [1, 2, 3, 4, 5]
a[:2] = [4, 5] # u pyhtonu ce slicing sa lijeve strane dati view na orginalnu listu
a

[4, 5, 3, 4, 5]

In [137]:
b = a[:2] # ali ako u pythonu imamo slicing s desne strane onda se stvori kopija liste
print(b)
b[0] = 123
print(b)
print(a)

[4, 5]
[123, 5]
[4, 5, 3, 4, 5]


In [139]:
a = np.array([1, 2, 3, 4, 5])
a[:2] = 22    # u numpyu se sa slicajnem s lijeve strane isto dobije view na orginalni array
a             # u numpyu naravno je omogucen BRODCASTING pa mogu samo dodijeliti 22 koji ce se prosiriti

array([22, 22,  3,  4,  5])

In [141]:
b = a[:2]            # !!!!! ali numpy ce s desne strane za razliku od obicnog pythona DATI view na orginalni
print(b)
b[:2] = 33           # To znaci da kada mijenjamo sada ovaj b, Zapravo kroz njega mijenjamo i ORGINALNI ndarray a
print(b)
print(a)

[22 22]
[33 33]
[33 33  3  4  5]


In [4]:
a = np.array([1, 2, 3, 4, 5])
b = a[:]
b[0] = 10
a

array([10,  2,  3,  4,  5])

In [6]:
c = a[:].copy()
c[0] = 23
print(c)
print(a)

[23  2  3  4  5]
[10  2  3  4  5]


#### ViseDimenzionalni slicing

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# pojedinacni element
print(a[0][0])
print(a[0, 0])

print(a[0])

1
1
[1 2 3 4]


In [13]:
# neki specficna slice
print(a[:2, :2])
# opet je viewset na orginalo polje
a[:2, :2] = 5
print(a)

[[1 2]
 [5 6]]
[[ 5  5  3  4]
 [ 5  5  7  8]
 [ 9 10 11 12]]


In [18]:
b = a[:, :1]
print(b)
b = a[:, 0]
print(b)

[[5]
 [5]
 [9]]
[5 5 9]


In [21]:
print(a)
print(a[0])
b = a[0]
b[:] = 3
print(a)

[[ 5  5  3  4]
 [ 5  5  7  8]
 [ 9 10 11 12]]
[5 5 3 4]
[[ 3  3  3  3]
 [ 5  5  7  8]
 [ 9 10 11 12]]


### Bollean Indexing

In [22]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [24]:
print(names[names == "Bob"]) # unutra se zapravo vrait polje
boolean_mask = names == "Joe"
names[boolean_mask]

['Bob' 'Bob']


array(['Joe', 'Joe', 'Joe'], dtype='<U4')

In [5]:
# di to moze biti super korisno
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data_height = np.array([180, 120, 145, 123, 456, 567, 789])
data_height[names == "Bob"]                     # visine svih Bobova

array([180, 123])

In [6]:
# takoder se nakon filtriranja odmah moze i indeksiran
data_height[names == "Bob"][0]

180

In [7]:
data_height[names != "Bob"]

array([120, 145, 456, 567, 789])

In [12]:
print(~(names == "Bob"))
print((names == "Bob") | (names == "Will"))
print((names == "Bob") & (names == "Will"))

[False  True  True False  True  True  True]
[ True False  True  True  True False False]
[False False False False False False False]


In [22]:
# Indeksiranje s boolean irazom, vrijednost s desnse strane ce se dodijeliti svima koji s lijeve strane imaju True
names = names.astype("<U10")
names[names == "Bomb"] = "Bombastic"
names

array(['Bombastic', 'Bombastic', 'Will', 'Bombastic', 'Will', 'Bombastic',
       'Bombastic'], dtype='<U10')

#### Fancy indexing

In [30]:
# kada se preda lista indexa koji specificiraju po kojem tocno redu zelimo da se vrait elementi unutar ndarraya
a = np.array([[i for j in range(5)] for i in range(5)])
b = np.array([[j for j in range(5)] for i in range(5)])
print(a)
print(a[[2, 4, 0]])   # opet cemo dobiti ndarray ali kopiju
print(b)
print(b[:, [2, 1, 0]])  # moze raidit i z aredke i za stupce, tj za sve dimenzije

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[2 2 2 2 2]
 [4 4 4 4 4]
 [0 0 0 0 0]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[2 1 0]
 [2 1 0]
 [2 1 0]
 [2 1 0]
 [2 1 0]]


In [31]:
# reshape je mocna stvar, moze promjeniti oblik naseg nd arraya kako god zelimo, dokle imamo dobar broj elemenata
a = np.arange(32).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [34]:
# SA fancy indexirajem ZAPRAVO mozemo odabrait i pojedinacne elemente u ndarrayu,
# TAKo da se gledaju parovi x i y  i odberu se ti elemeenit koji se traze

print(a[[0, 1, 2, 3],[0, 1, 2, 3]])  # uzmemo proizvoljene elmente sa kombinacijom

# print(a[[1:3, 4, 5], [0] * 4]) # nije moguce kombinirait fancy indexiranje i slicanje

[ 0  5 10 15]


### Operacije s matricama, transponiranje , reshaping i to

In [36]:
a = np.arange(16).reshape((4, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
b = a.T         # Transponiranje je i dalje view na orginal
print(b)
b[0][1] = 44
print(b)
print(a)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0 44  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  1  2  3]
 [44  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [49]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
print(a.shape)
print(b.T.shape)
print(a.T @ b)
print(a @ b)

(5,)
(5,)
55
55


In [56]:
a = np.array([1, 2, 3, 4, 5]).reshape((1, 5))
b = np.array([1, 2, 3, 4, 5]).reshape((1, 5))
print(a)
print(b.T)
print(a @ b.T)
print(a.T @ b)
print(np.dot(a.T, b)) # ista stvar

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[55]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [57]:
# ako zelimo samo element vise
a * b # svaki eelment sa svojim elementom koji mu odgovara

array([[ 1,  4,  9, 16, 25]])

### Mijenjanje dimenzija i osi

In [60]:
a = np.arange(16).reshape((2, 8))
print(a)
print(np.swapaxes(a, 0, 1))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]


In [68]:
b = np.ones(8)
a = np.array([[[1, 2, 3, 4, 5]]])
print(b)
print(np.expand_dims(b, 0))
print(np.expand_dims(b, 1)) # doda jednu dimenziju
print()
print(a)
print(np.squeeze(a, 0)) # makne jednu dimenziju
print(a.flatten()) # sve spoljsti


[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

[[[1 2 3 4 5]]]
[[1 2 3 4 5]]
[1 2 3 4 5]


### Pseudo random number generator

Numpy.random modul je mocan jer nam omogucava:
1. da odmah dobijemo cijelo polje nasumicnih vrijednosti
2. da te vrijednosti budu iz proizvoljnih distirbucija

Numpy je puno brzi kada treba generirarti velik ekolicine podataka, jer random iz obicnog pythona stvara vrijednost po vrijednost

In [71]:
a = np.random.standard_normal((4, 4))
a

array([[-0.31590065, -0.31361397,  0.23826884,  1.00263279],
       [-0.68114512,  0.19372765,  0.43014414,  0.04627935],
       [ 0.35415096,  1.38158897,  1.01985482, -1.60281353],
       [ 2.13013034,  0.60167653,  0.19155106,  0.64860102]])

In [75]:
b = np.random.standard_normal(10)
b

array([ 0.04404151, -1.76629643, -1.78296664,  0.53757574,  0.10599528,
       -0.94655292, -1.55084942,  0.09953335, -0.84628996,  0.57883014])

In [77]:
rng = np.random.default_rng() # random number generator object
rng.standard_normal((2, 2))

array([[-1.05723793,  1.30814385],
       [ 0.10034306, -0.23259763]])

In [85]:
print(rng.permutation(range(15))) # random permutacija
a = [1, 2, 3, 4]
rng.shuffle(a)
print(a)
print(rng.uniform(2, 5, (2, 2)))
print(rng.normal(0, 1, (2, 2)))

[ 0  8  2  3  1  7  6 14 12  4 10 13 11  5  9]
[2, 1, 3, 4]
[[2.77699075 3.52134031]
 [4.81112889 4.46123326]]
[[-0.05505749  0.22120945]
 [-0.57360011 -1.08574244]]


### Univerzalne funkcije

Univerzalne funkcije ili ti *ufunc* su samo funkcije koje djeluju na cijeli ndarray i vracaju ndarray

Ufunc-s u pravilu uvijek vracaju Novo polje, tj ne vracaju view nego novo polje

In [88]:
a = [1, 2, 3, 4, 5]
np.sqrt(a) # ista stavr samo vrait ndarray sa korijenovanvim vrijednostima
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [97]:
a = np.array([1, 2.3, 3, 4, 5, 6])
b = np.array([5, 5, 5, 5, 5, 5])
np.maximum(a, b)            # binary ufunc,   ono gore su bili unary ufuncs
np.minimum(a, b)
print(a + b)


[ 6.   7.3  8.   9.  10.  11. ]


In [99]:
# ima i hrpa hrpa drugih ufunc-cija , npr floor, sign ceil expt cos sin...
np.ceil(a) # ...

array([1., 3., 3., 4., 5., 6.])

In [100]:
a = np.array([0.1, 0.5, -0.3])
np.sin(a)

array([ 0.09983342,  0.47942554, -0.29552021])

In [102]:
a = np.append(a, 1)
a

array([ 0.1,  0.5, -0.3,  1. ])

In [108]:
a = np.array([[1], [2]])
b = np.array([[1], [2]])

print(a)
print(b)
print(np.hstack([a, b]))
print(np.vstack([a, b]))

[[1]
 [2]]
[[1]
 [2]]
[[1 1]
 [2 2]]
[[1]
 [2]
 [1]
 [2]]


### Linearna algebra

In [111]:
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [116]:
a = np.full((4, 4), fill_value=3)
np.linalg.det(a) # Determinanta
# np.linalg.inv(a) # Inverz
np.linalg.norm(a) # Norma - tj velicina matrice ili vektora

12.0

In [117]:
a.T

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [125]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))
np.argmax(a)  # !!! ovo moze biti dosta bitno i krosino, vrati element di se postize najveca vrijendost


10
[ 6  7  8  9 10]
[ 5 10]


9

In [126]:
np.mean(a)

5.5

In [127]:
np.std(a)

2.8722813232690143

kako pretvoriti nazad u obicnu pyhton listu:

In [129]:
print(a)
print(a.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [132]:
## generiranje liste on n brojeva koji jednoliko idu od prvog do drugog  a stpe je koliki je n pa izmedu prvog i drugog
b = np.linspace(1, 10, 100, dtype=np.int64)
b

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10])

In [133]:
c = np.linspace(1, 10, 5)
c

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [134]:
c.tolist()

[1.0, 3.25, 5.5, 7.75, 10.0]

### neke ostale stavri

In [136]:
# efektinvo if else condition
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
rezz = np.where(cond, xarr, yarr) # uzmi x tamo di je uvjet istinit inace y
print(rezz)

[1.1 2.2 1.3 1.4 2.5]


In [137]:
polje = np.random.standard_normal((4, 4))
a = np.where(polje > 0, 2, -2)
a

array([[ 2,  2,  2, -2],
       [-2, -2, -2,  2],
       [ 2,  2,  2,  2],
       [-2, -2, -2,  2]])

In [140]:
arr = np.arange(16).reshape((4, 4))
print(arr)
print(arr.sum(axis=0)) # po okomotj osi ce ih zbrojiti, mkanuti ce jendu dimenziju

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 28 32 36]


In [141]:
(arr > 10).sum()

5

In [142]:
(arr > 10).any()     # u obicnom pythonu bi to bilo any(i onda neka lsit aboolen stvari) OVDJE se to poziva DIREKTNO NAD                        np arrayom
(arr > 10).all()

False

In [144]:
arr.sort()
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])